[icons]
name = "awesome"
#
[theme]
name = "plain"
[theme.overrides]
separator = " | "
idle_bg = "#123456"
idle_fg = "#abcdef"
info_bg = "#123456"
good_bg = "#123456"
separator_bg = "#123456"
#
[[block]]
block = "focused_window"
max_width = 50
#
[[block]]
block = "net"
device = "wlp5s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_down = true
interval = 3
use_bits = false
#
[[block]]
block = "disk_space"
path = '/'
alias = ''
info_type = "available"
unit = "GB"
show_percentage = true
interval = 20
warning = 20.0
alert = 10.0
#
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
#
[[block]]
block = "cpu"
interval = 1
#
[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"
#
[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
